import { BrandMark } from "@/components/BrandMark";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { historyMoments, referenceSources, studyRoutes } from "../../../lib/legal-learning";
import { ArrowLeft, ArrowRight, BookOpen, Brain, Compass, ExternalLink, FileText, Landmark, ShieldCheck, Sparkles, Target } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const HERO_IMAGE = "/manus-storage/legal-history-library-hero_573d9289.png";
const SOLOMON_IMAGE = "/manus-storage/legal-history-solomon-v2_1086cbef.png";
const NUREMBERG_IMAGE = "/manus-storage/legal-history-nuremberg-v2_dbcb7c11.png";
const TIMELINE_IMAGE = "/manus-storage/legal-history-timeline_4ff31ce7.png";

const routeIcons = [Brain, FileText, Target, ShieldCheck];

export default function HistoryOfAdvocacy() {
  const [, navigate] = useLocation();
  const [activeRoute, setActiveRoute] = useState(studyRoutes[0].id);
  const selectedRoute = studyRoutes.find((route) => route.id === activeRoute) ?? studyRoutes[0];

  return <div className="min-h-screen overflow-x-hidden bg-[#fbf8f1] text-[#102a43]">
    <header className="sticky top-0 z-50 border-b border-[#e8dec9]/80 bg-[#fbf8f1]/90 backdrop-blur-xl"><div className="container flex h-[4.8rem] items-center justify-between gap-4"><button type="button" onClick={() => navigate("/")} className="shrink-0" aria-label="Ir a LegalDoc"><BrandMark /></button><nav className="hidden items-center gap-7 md:flex" aria-label="Navegación de biblioteca"><button type="button" onClick={() => document.getElementById("linea-tiempo")?.scrollIntoView({ behavior: "smooth" })} className="legal-nav-link">Línea de tiempo</button><button type="button" onClick={() => document.getElementById("aprendizaje")?.scrollIntoView({ behavior: "smooth" })} className="legal-nav-link">Rutas de aprendizaje</button></nav><Button variant="outline" onClick={() => navigate("/")} className="rounded-xl border-[#cdbb96] bg-[#fffdf8] text-[#284458] hover:bg-[#f4ecdd]"><ArrowLeft className="mr-2 h-4 w-4" />Inicio</Button></div></header>
    <main>
      <section className="relative border-b border-[#e7dbc3] bg-[#102a43] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(214,169,86,.18),transparent_28%),linear-gradient(110deg,#0e2941_0%,#102a43_50%,#183d53_100%)]" /><div className="container relative grid min-h-[625px] items-center gap-10 py-14 lg:grid-cols-[.98fr_1.02fr] lg:py-18"><div className="relative z-10 max-w-2xl"><div className="flex flex-wrap items-center gap-3"><Badge className="border border-[#f4d98d]/35 bg-[#f4d98d]/10 px-3 py-1 text-[.65rem] font-extrabold uppercase tracking-[.16em] text-[#f5d98b] hover:bg-[#f4d98d]/10">Biblioteca de la abogacía</Badge><span className="text-xs font-semibold text-[#c9d5dd]">Historia · criterio · aprendizaje continuo</span></div><p className="mt-8 text-xs font-extrabold uppercase tracking-[.18em] text-[#f5d98b]">Un oficio que se sigue aprendiendo</p><h1 className="mt-5 font-display text-[3.25rem] font-semibold leading-[.9] tracking-[-.055em] sm:text-[4.4rem] lg:text-[5.15rem]">La historia detrás de <span className="text-[#f3d58c]">cada argumento.</span></h1><p className="mt-7 max-w-xl text-[1rem] leading-8 text-[#cbd7df] sm:text-lg">Explora momentos, dilemas y métodos que invitan a ejercer la abogacía con más profundidad. Una biblioteca para detenerse, estudiar y volver al caso con mejor criterio.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={() => document.getElementById("linea-tiempo")?.scrollIntoView({ behavior: "smooth" })} size="lg" className="rounded-xl bg-[#f5d98b] px-6 font-extrabold text-[#102a43] hover:bg-[#ffe6a0]">Recorrer la historia <ArrowRight className="ml-2 h-4 w-4" /></Button><Button onClick={() => document.getElementById("aprendizaje")?.scrollIntoView({ behavior: "smooth" })} size="lg" variant="outline" className="rounded-xl border-white/25 bg-white/5 px-6 text-white hover:bg-white/10 hover:text-white">Ver rutas de aprendizaje</Button></div></div><div className="relative mx-auto w-full max-w-[680px]"><div className="absolute -inset-6 rounded-[2.5rem] bg-[#e7b65c]/15 blur-3xl" /><div className="relative overflow-hidden rounded-[1.9rem] border border-white/15 bg-white/5 p-2 shadow-[0_30px_80px_rgba(0,0,0,.26)]"><img src={HERO_IMAGE} alt="Biblioteca editorial donde dialogan textos jurídicos y la historia del derecho" className="h-[400px] w-full rounded-[1.45rem] object-cover sm:h-[500px]" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/15 bg-[#0c243b]/88 p-4 backdrop-blur-md"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#f5d98b] text-[#102a43]"><BookOpen className="h-4 w-4" /></div><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#f3d58c]">Principio editorial</p><p className="mt-0.5 text-sm font-semibold text-white">Las fuentes se muestran; las lecciones se distinguen.</p></div></div></div></div></div></div></section>

      <section className="container py-10 sm:py-14"><div className="rounded-2xl border border-[#d9c7a5] bg-[#fffaf0] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f1eadc] text-[#8c6b35]"><Compass className="h-5 w-5" /></div><div><p className="text-sm font-extrabold text-[#284458]">Una sala de estudio, no un sustituto de criterio profesional.</p><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-600">Esta biblioteca ofrece contexto histórico y recursos de aprendizaje. Los relatos culturales se identifican como tales; las fuentes se enlazan para que puedas contrastar el contenido. No constituye asesoría jurídica ni reemplaza la verificación de normas vigentes.</p></div></div></div></section>

      <section id="linea-tiempo" className="border-y border-[#e8dec9] bg-[#f4eee1]/58 py-20 lg:py-28"><div className="container"><div className="overflow-hidden rounded-[1.8rem] border border-[#dfd1b6] bg-[#fffaf0]"><div className="relative min-h-[185px] border-b border-[#dfd1b6] bg-[#e9dfcb]"><img src={TIMELINE_IMAGE} alt="Objetos editoriales que evocan la continuidad de la historia jurídica" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#fffaf0]/72 via-transparent to-[#102a43]/10" /><div className="relative p-6 sm:p-8"><p className="legal-kicker">Línea de tiempo</p><p className="mt-2 max-w-sm text-sm leading-6 text-[#385365]">Una selección editorial de voz, poder, evidencia y responsabilidad.</p></div></div><div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[.72fr_1.28fr]"><div><h2 className="font-display text-5xl font-semibold leading-[.94] tracking-[-.045em] text-[#102a43]">Cuatro puertas para <span className="text-[#8c6b35]">pensar el oficio.</span></h2><p className="mt-6 max-w-sm leading-7 text-slate-600">No es una historia total del derecho. Es una selección editorial para observar cómo dialogan voz, poder, evidencia y responsabilidad.</p></div><div className="relative space-y-4 before:absolute before:bottom-6 before:left-[1.15rem] before:top-6 before:w-px before:bg-[#d9c7a5]">{historyMoments.map((moment, index) => <article key={moment.title} className="legal-surface legal-hover-lift relative ml-0 rounded-2xl p-6 pl-16"><span className="absolute left-[.62rem] top-8 grid h-5 w-5 place-items-center rounded-full border-4 border-[#f4eee1] bg-[#8c6b35]" /><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#8c6b35]">{moment.period}</p><Badge variant="outline" className={moment.kind === "cultural" ? "border-[#b8a27e] bg-[#fffaf0] text-[.6rem] uppercase tracking-[.12em] text-[#755725]" : "border-[#b6c7bb] bg-[#f2f7f1] text-[.6rem] uppercase tracking-[.12em] text-[#37624a]"}>{moment.kind === "cultural" ? "Relato cultural" : "Hito histórico"}</Badge></div><h3 className="mt-3 text-xl font-extrabold text-[#284458]">{moment.title}</h3></div><span className="font-display text-3xl text-[#d2bc91]">0{index + 1}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{moment.context}</p><div className="mt-5 border-l-2 border-[#d8c49e] pl-4"><p className="text-[.65rem] font-extrabold uppercase tracking-[.13em] text-[#8c6b35]">Lección para el oficio</p><p className="mt-1 text-sm font-semibold leading-6 text-[#284458]">{moment.lesson}</p></div><a href={moment.sourceUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center text-xs font-extrabold text-[#1d4b6e] hover:text-[#8c6b35]">Fuente: {moment.sourceLabel}<ExternalLink className="ml-1.5 h-3.5 w-3.5" /></a></article>)}</div></div></div></div></section>

      <section className="container py-20 lg:py-28"><div className="mb-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="legal-kicker">Casos para detenerse</p><h2 className="mt-3 font-display text-5xl font-semibold leading-none tracking-[-.045em] text-[#102a43]">Historias que obligan a mirar dos veces.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-600">Cada estudio propone preguntas; no entrega fórmulas para trasladar mecánicamente a casos reales.</p></div><div className="grid gap-5 lg:grid-cols-2"><CaseCard image={SOLOMON_IMAGE} eyebrow="Relato cultural · 1 Reyes 3" title="¿Qué revela una respuesta bajo presión?" body="El relato atribuido a Salomón permite conversar sobre intereses, escucha y el riesgo de tomar una reacción como prueba definitiva." questions={["¿Qué se sabe y qué se infiere?", "¿Qué pregunta reduce la incertidumbre?", "¿Qué límites éticos debe tener una estrategia?"]} href="https://bible.usccb.org/bible/1kings/3" /><CaseCard image={NUREMBERG_IMAGE} eyebrow="Hito histórico · 1945–1946" title="El expediente como garantía de memoria." body="Núremberg ofrece una puerta para estudiar jurisdicción, prueba y la responsabilidad que acompaña a la documentación de hechos graves." questions={["¿Qué hace trazable una afirmación?", "¿Cómo se contrasta una transcripción?", "¿Qué debe preservar un expediente?"]} href="https://nuremberg.law.harvard.edu/" /></div></section>

      <section id="aprendizaje" className="border-y border-[#e8dec9] bg-[#102a43] py-20 text-white lg:py-28"><div className="container"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.17em] text-[#f3d58c]">Aprendizaje continuo</p><h2 className="mt-4 font-display text-5xl font-semibold leading-[.94] tracking-[-.045em]">La técnica se entrena.<br /><span className="text-[#f3d58c]">El criterio también.</span></h2><p className="mt-6 max-w-sm leading-7 text-[#c8d4df]">Recorridos breves para practicar competencias transferibles entre materias, escritos y conversaciones con clientes.</p><div className="mt-8 rounded-xl border border-white/15 bg-white/5 p-4 text-sm leading-6 text-[#dce6eb]"><Sparkles className="mb-2 h-4 w-4 text-[#f3d58c]" />Elige una ruta y úsala como una pauta de estudio; después llévala a tus fuentes y casos reales.</div></div><div className="grid gap-3">{studyRoutes.map((route, index) => { const Icon = routeIcons[index]; const selected = route.id === activeRoute; return <button key={route.id} type="button" onClick={() => setActiveRoute(route.id)} className={`rounded-2xl border p-5 text-left transition ${selected ? "border-[#f3d58c]/50 bg-[#f3d58c]/12 shadow-[0_16px_36px_rgba(0,0,0,.12)]" : "border-white/10 bg-white/[.035] hover:border-white/25 hover:bg-white/[.07]"}`}><div className="flex gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/10" style={{ color: selected ? "#f3d58c" : "#c8d4df" }}><Icon className="h-5 w-5" /></div><div><p className="text-[.65rem] font-extrabold uppercase tracking-[.14em] text-[#f3d58c]">{route.eyebrow}</p><h3 className="mt-1 text-lg font-extrabold">{route.title}</h3><p className="mt-2 text-sm leading-6 text-[#c8d4df]">{route.description}</p>{selected && <div className="mt-4 flex flex-wrap gap-2">{route.modules.map((module) => <span key={module} className="rounded-lg border border-white/15 bg-[#0d263d] px-2.5 py-1.5 text-xs font-bold text-white">{module}</span>)}</div>}</div></div></button>; })}</div></div><div className="mt-10 rounded-2xl border border-white/10 bg-white/[.045] p-5 sm:p-6"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#f3d58c]">Ahora exploras</p><div className="mt-2 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-lg font-extrabold">{selectedRoute.title}</p><p className="mt-1 text-sm text-[#c8d4df]">{selectedRoute.modules.join(" · ")}</p></div><Button onClick={() => navigate("/catalogo")} className="w-fit rounded-xl bg-[#f5d98b] font-extrabold text-[#102a43] hover:bg-[#ffe6a0]">Volver a la práctica <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></div></section>

      <section className="container py-20 lg:py-24"><div className="grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><p className="legal-kicker">Referencias abiertas</p><h2 className="mt-3 font-display text-4xl font-semibold leading-[.96] tracking-[-.04em] text-[#102a43]">Sigue las fuentes.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-slate-600">Las fuentes consultadas permanecen visibles para facilitar el contraste, la lectura ampliada y la corrección editorial.</p></div><div className="grid gap-3">{referenceSources.map((source, index) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="legal-surface legal-hover-lift group flex gap-4 rounded-xl p-4"><span className="font-display text-2xl text-[#d2bc91]">0{index + 1}</span><div className="min-w-0 flex-1"><p className="font-extrabold text-[#284458] group-hover:text-[#8c6b35]">{source.label}</p><p className="mt-1 text-sm leading-6 text-slate-600">{source.note}</p></div><ExternalLink className="mt-1 h-4 w-4 shrink-0 text-[#8c6b35]" /></a>)}</div></div></section>
    </main>
    <footer className="border-t border-[#e8dec9] bg-[#f7f1e5] py-10"><div className="container flex flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><BrandMark /><div className="max-w-md text-sm leading-6 text-slate-500 sm:text-right"><p>LegalDoc integra herramientas de redacción y aprendizaje jurídico.</p><p className="mt-1">Los contenidos educativos se complementan con fuentes visibles y revisión profesional.</p></div></div></footer>
  </div>;
}

function CaseCard({ image, eyebrow, title, body, questions, href }: { image: string; eyebrow: string; title: string; body: string; questions: string[]; href: string }) { return <article className="group overflow-hidden rounded-2xl border border-[#dfd1b6] bg-[#fffdf8] shadow-[0_10px_28px_rgba(31,50,67,.06)]"><div className="relative overflow-hidden"><img src={image} alt="Ilustración editorial para estudio de caso jurídico" className="h-64 w-full object-cover transition duration-500 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-[#102a43]/55 via-transparent to-transparent" /><span className="absolute bottom-4 left-5 rounded-full border border-white/25 bg-[#102a43]/85 px-3 py-1 text-[.62rem] font-extrabold uppercase tracking-[.13em] text-[#f3d58c] backdrop-blur">{eyebrow}</span></div><div className="p-6"><h3 className="font-display text-3xl font-semibold leading-[.98] tracking-[-.035em] text-[#284458]">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{body}</p><div className="mt-5 border-t border-[#e6dbc7] pt-5"><p className="text-[.65rem] font-extrabold uppercase tracking-[.13em] text-[#8c6b35]">Preguntas de estudio</p><ul className="mt-3 space-y-2">{questions.map((question) => <li key={question} className="flex gap-2 text-sm font-semibold text-[#284458]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#c69d59]" />{question}</li>)}</ul></div><a href={href} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center text-xs font-extrabold text-[#1d4b6e] hover:text-[#8c6b35]">Abrir fuente <ExternalLink className="ml-1.5 h-3.5 w-3.5" /></a></div></article>; }
